disabled_rules: # rule identifiers to exclude from running
  - file_header # Want this on, can't figure out what exactly its checking for
  - type_name
  - opening_brace
  - nesting
  - function_body_length
  - blanket_disable_command

opt_in_rules: # some rules are only opt-in
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_parameter_count
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nslocalizedstring_key
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - prohibited_interface_builder
  - prohibited_super_call
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - xct_specific_matcher

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - fastlane
  - vendor
  - .build

function_parameter_count: 8
line_length:
    warning: 140
    ignores_comments: true
file_length: 600

identifier_name:
  min_length: 3
  max_length:
    warning: 40
    error: 80
  excluded:
    - id
