name: Deploy Documentation

on:
  # Run any time code is pushed to main.
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    name: Publish Documentation
    uses: krogerco/Shared-CI-Workflow-iOS/.github/workflows/pages.yml@feature/pages
    with:
      FILENAME: Gauntlet.xcworkspace
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
