name: Check for Sign Off

on:     
  pull_request:
    types: [unlabeled]
  pull_request_review:
    types: [submitted]

jobs:
  sign-off-check:
    name: Check sign-off
    runs-on: ubuntu-latest
    steps:
      - name: sign off
        uses: krogerco/Shared-CI-Workflow-iOS/.github/workflows/qa.yml@feature/initial
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
