name: Check for Sign Off

on:     
  pull_request:
    types: [unlabeled]
  pull_request_review:
    types: [submitted]

jobs:
  sign-off-check:
    name: Check sign-off
    runs-on: ubuntu-latest
    steps:
      - name: sign off
        uses: krogertechnology/sign-off@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
